SELECT USER_ID,NICKNAME,SUM_PRICE AS TOTAL_SALES
    FROM USED_GOODS_USER AS U INNER JOIN 
        (SELECT B.WRITER_ID, SUM(B.PRICE) AS SUM_PRICE
            FROM USED_GOODS_BOARD B WHERE B.STATUS = 'DONE'
            GROUP BY B.WRITER_ID) AS T
        ON U.USER_ID = T.WRITER_ID
    WHERE SUM_PRICE>=700000
    ORDER BY SUM_PRICE
